---

name: Lint

on:
  push:
    branches: [latest, v*]
    paths:
      - '**.go'
      - '.github/workflows/lint.yml'
      - 'scripts/lint.sh'
      - '.golangci_warn.yml'
      - '.golangci_fail.yml'
  pull_request:
    branches: [latest, v*]
    paths:
      - '**.go'
      - '.github/workflows/lint.yml'
      - 'scripts/lint.sh'
      - '.golangci_warn.yml'
      - '.golangci_fail.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'src/go.mod'

      # NOTE: not using 'golangci/golangci-lint-action' because of warn/error split
      - name: Install dependencies
        run: |
          sudo apt install curl
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.6.0

      - name: Verifying golangci-lint
        run: |
          which golangci-lint
          golangci-lint version

      - name: Linting
        run: bash scripts/lint.sh
